# Generated by Django 6.0.4 on 2026-04-26 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tariffs',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('billing_month', models.DateField()),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tariff_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.smartmeter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-billing_month'],
            },
        ),
    ]
