# Generated by Django 6.0.4 on 2026-04-26 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('reported', 'User Reported'), ('detected', 'System Detected'), ('potential', 'Potential Leak')], max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Confirmed'), ('in_progress', 'Under Repair'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='detected', max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaks/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_water_loss', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leaks', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leak_reports', to='meters.smartmeter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leak_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leak_reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
