# Generated by Django 6.0.4 on 2026-04-26 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('meter_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('faulty', 'Faulty')], default='active', max_length=20)),
                ('last_reading', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('last_reading_date', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20)),
                ('battery_level', models.IntegerField(default=100)),
                ('signal_strength', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_meters',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.smartmeter')),
            ],
            options={
                'db_table': 'meter_readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
