# Generated by Django 6.0.4 on 2026-04-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='smartmeter',
            options={'ordering': ['-installation_date']},
        ),
    ]
